LBHackney-IT/housing-needs-single-view-ui

- .circleci/config.yml
Reverts LBHackney-IT/housing-needs-single-view-proto-ui#3
> Revert "fix how params are set based on stages"

- src/Components/Details/QuickAccess/CaseInformation/index.jsx
Replace Jigsaw training link with the live link
> Jigsaw link

- src/Components/Details/ContactDetails/index.jsx
> Add new lines between phones

- src/Components/Details/QuickAccess/CaseInformation/index.jsx
> Remove PHP link if id does not exist

- src/Components/Details/QuickAccess/CouncilTax/index.jsx
- src/Components/Details/QuickAccess/HousingRegister/index.jsx
- src/Components/Details/SystemIds/index.jsx
- src/lib/Utils.js
Should be committed together with this SV api PR: https://github.com/LBHackney-IT/housing-needs-single-view-proto-api/pull/39
> Lets the UI display all housing register applications

- cypress/integration/acceptance/search.spec.js
- cypress/integration/pages/details.spec.js
- cypress/support/commands.js
> Testing retest

- src/app/Components/Details/Note/index.jsx
- src/app/css/overrides.scss
> Make documents link have yellow background on click and be lighter green on hover

- cypress/integration/acceptance/search.spec.js
- cypress/integration/pages/results.spec.js
- src/app/Components/Results/PreviousRecord/index.scss
- src/app/Pages/ResultsPage/index.jsx
Move connect records button to the top and disable it if no records are selected
> Connect records button

- cypress/integration/pages/details.spec.js
- src/FakeSVapi.js
- src/app/Components/Details/QuickAccess/HousingRegister/index.jsx
- src/app/Components/Details/QuickAccess/index.jsx
In this PR I've added bedroom requirements to housing register information along with tests for Quick Access panel.
> Displaying bedroom requirements

- cypress/integration/pages/details.spec.js
- src/FakeSVapi.js
- src/app/Components/Details/QuickAccess/HousingRegister/index.jsx
In this PR I added application status to housing register information and I added a test for it.
> Application status

- src/app/Pages/LoginPage/index.jsx
- src/app/css/overrides.scss
This PR adds privacy notice to the log in page.
> Adding privacy notice to the log in page

- .circleci/config.yml
- cypress.json
- cypress/integration/acceptance/search.spec.js
- cypress/integration/pages/results.spec.js
- package-lock.json
- package.json
- src/FakeSVapi.js
- src/app/Components/Header/index.jsx
- src/app/Pages/DetailsPage/index.jsx
- src/app/Pages/ResultsPage/index.jsx
- src/app/css/overrides.scss
- src/app/lib/Utils.js
**Might be #6 on Single View: Accessibility testing basic check report**
> Styling when there are no records to connect

- public/index.html
- src/app/Pages/DetailsPage/index.jsx
- src/app/Pages/LoginPage/index.jsx
- src/app/Pages/ResultsPage/index.jsx
- src/app/Pages/SearchPage/index.jsx
- src/app/Pages/VulnerabilitiesPage/index.jsx
**#3, 4 and 9 on Single View: Accessibility testing basic check report**
> Add page titles

- src/app/Components/Phase/index.jsx
> Change banner to beta

- cypress/integration/pages/details.spec.js
- src/app/Components/Details/Activity/index.jsx
- src/app/Components/Details/ActivitySearch/index.jsx
- src/app/Components/Details/ActivitySearch/index.scss
- src/app/Components/Details/AddressDetails/index.jsx
- src/app/Components/Details/ContactDetails/index.jsx
- src/app/Components/Details/Note/index.jsx
- src/app/Components/Details/PersonalDetails/index.jsx
- src/app/Components/Details/QuickAccess/Benefits/index.jsx
- src/app/Components/Details/QuickAccess/CaseInformation/index.jsx
- src/app/Components/Details/QuickAccess/CouncilTax/index.jsx
- src/app/Components/Details/QuickAccess/HousingRegister/index.jsx
- src/app/Components/Details/QuickAccess/Tenancy/index.jsx
- src/app/Components/Details/SystemIds/index.jsx
- src/app/Components/Details/Team/index.jsx
- src/app/Components/DocumentModal/index.jsx
- src/app/Components/Modal/index.jsx
- src/app/Components/Results/GroupedTable/index.jsx
- src/app/Components/Results/GroupedTable/index.scss
- src/app/Components/Results/PreviousRecord/index.jsx
- src/app/Components/Results/RecordsTable/index.jsx
- src/app/Components/Results/RecordsTable/index.scss
- src/app/Pages/ResultsPage/index.jsx
- src/app/css/overrides.scss
Change broken links into buttons
Change table structure
Changed underlined text into a button
> Address Medium and Low accessibility assessment outcomes

- .circleci/config.yml
- babel.config.js
- jest.config.js
- package-lock.json
- package.json
- src/app/App.test.js
- src/app/Components/Details/ActivitySearch/index.jsx
- src/app/Components/PrivateRoute/index.js
- src/app/Pages/ResultsPage/index.jsx
- src/app/lib/FeatureFlag.js
- src/app/lib/FeatureFlag.test.js
WHAT
Store url hashes for a logged in user in a cookie
WHY
I want to be able to turn on a feature flag for a user by giving them a url to open
> Set user feature flags via url hash

- package-lock.json
- package.json
- src/app/Components/Details/ThingsToNote/index.jsx
- src/app/Components/Details/index.js
- src/app/Gateways/CreateVulnerability.js
- src/app/Gateways/CreateVulnerability.test.js
- src/app/Pages/DetailsPage/index.jsx
WHAT
Add a button to create a vulnerability snapshot and redirect to vulnerability app
> Add create snapshot ui

- cypress/FakeSVapi.js
- cypress/fixtures/snapshot.json
- cypress/integration/pages/details.spec.js
- package-lock.json
- package.json
- src/app/Components/Details/ThingsToNote/SnapshotSummary/index.jsx
- src/app/Components/Details/ThingsToNote/SnapshotSummary/index.module.scss
- src/app/Components/Details/ThingsToNote/index.jsx
- src/app/Gateways/FindLatestSnapshot.js
- src/app/Gateways/FindLatestSnapshot.test.js
- src/app/css/styles.scss
**What**
Adds latest snapshot details to the "things to note" box on the details page.
**Why**
So that the latest vulnerabilities and strengths are highlighted when viewing the clients details.
**Anything else?**
- Added `classnames` for dealing with multiple CSS classes on components.
> Adds latest snapshot to "things to note" box

- cypress/fixtures/snapshot.json
- package-lock.json
- src/app/Components/Details/Note/SnapshotNoteContent.jsx
- src/app/Components/Details/ThingsToNote/SnapshotSummary/index.jsx
- src/app/Gateways/FindLatestSnapshot.js
- src/app/Gateways/FindLatestSnapshot.test.js
- src/app/Gateways/FindSnapshots.js
- src/app/Gateways/FindSnapshots.test.js
WHAT
Some minor UI changes for displaying the vulnerabilities
> Update vulnerabilities UI

- src/app/Components/Details/Note/NoteContent.jsx
- src/app/Components/Details/Note/SnapshotNoteContent.jsx
- src/app/Components/Details/Note/index.jsx
- src/app/Components/Details/ThingsToNote/SnapshotSummary/index.jsx
- src/app/Components/Details/ThingsToNote/SnapshotSummary/index.module.scss
- src/app/Components/Details/ThingsToNote/index.jsx
- src/app/Components/Details/ThingsToNote/index.module.scss
- src/app/Pages/DetailsPage/index.jsx
- Show snapshot "created by" user
- Update "things to note" box styles
- Expand/hide long snapshot notes
> Vulnerabilities ui updates

- .gitignore
- src/app/Pages/DetailsPage/index.jsx
Updated snapshot date to show the correct date in notes.
> Update snapshot date in notes to show correct date

- cypress/integration/pages/details.spec.js
- cypress/support/commands.js
- src/app/Components/Details/QuickAccess/index.jsx
- src/app/lib/auth-groups.json
**What**
Change shared plan feature flag to google groups
**Why**
To give access to shared plan based on google groups
> Change shared plan feature flag to google groups

- src/app/Gateways/Alphas/FindUploadedDocuments.js
- src/app/Gateways/Alphas/FindUploadedDocuments.test.js
- src/app/Pages/DetailsPage/index.jsx
**WHAT**
Find and show uploaded documents in activity feed
> Find and show uploaded documents in activity feed

- src/app/Components/Details/Note/index.jsx
- src/app/Gateways/Alphas/FindUploadedDocuments.js
- src/app/Gateways/Alphas/FindUploadedDocuments.test.js
- src/app/Gateways/Alphas/GetUploadedDocumentUrl.js
- src/app/Gateways/Alphas/GetUploadedDocumentUrl.test.js
- src/app/Pages/DetailsPage/index.jsx
**WHAT**
Adds the ability to download customer uploaded files from the SV activity feed
> Download customer uploaded files in activity feed

- cypress/integration/pages/details/request-documents/request-documents.spec.js
- src/app/Pages/DetailsPage/index.jsx
**What**
Remove request-documents feature flag
**Why**
To allow everyone to request documents from SV
> remove request-documents feature flag

- cypress/integration/acceptance/search.spec.js
- cypress/integration/pages/results.spec.js
- src/app/App.js
- src/app/Gateways/SearchTenancies.js
- src/app/Pages/AddressResultsPage/index.jsx
- src/app/Pages/SearchPage/index.jsx
Add UI for searching for residents by address and the option to filter the results
Add initial page for the results of searching to be able to test and in preparation for the ticket related to building the results page
> Sv 101/search by address

- cypress/fixtures/tenancyRecord.json
- cypress/integration/pages/tenancyDetails/tenancyDetails.spec.js
- src/app/Components/Details/HouseholdMembers/index.jsx
- src/app/Components/Details/index.js
- src/app/Pages/TenancyDetailsPage/index.jsx
- src/app/Pages/TenancyDetailsPage/index.scss
Adds a component which displays the other household members, pulled from the v1 API via MaT service API
> Add household members to tenancy view

- cypress/FakeSVapi.js
- cypress/fixtures/searchAddress.json
- cypress/integration/pages/searchAddress.spec.js
- cypress/integration/pages/searchAddressResults.spec.js
- src/app/Components/Results/AddressResults/index.jsx
- src/app/Components/Results/AddressResults/index.scss
- src/app/Components/Results/Dropdown/index.jsx
- src/app/Components/Results/index.js
- src/app/Gateways/index.js
- src/app/Pages/AddressResultsPage/index.jsx
- src/app/Pages/SearchPage/index.jsx
- Added results page for searching by address
- Added AddressResults component for the table
- Added Dropbox component for the dropdown list
> Address search results

- cypress/fixtures/tenancyRecord.json
- cypress/integration/pages/tenancyDetails/tenancyDetails.spec.js
- src/app/Components/Details/TenancyPatchDetails/index.jsx
- src/app/Pages/TenancyDetailsPage/index.jsx
- Updated Area and Patch section to contain tenancy patch, tenancy area and officer name
> Area and patch

- cypress/fixtures/tenancyRecord.json
- cypress/integration/pages/tenancyDetails/tenancyDetails.spec.js
- src/app/Components/Details/HouseholdMembers/index.jsx
- src/app/Components/Details/TenancyProcesses/index.jsx
- src/app/Components/Details/TenancyProcesses/index.scss
- src/app/Components/Details/index.js
- src/app/Pages/TenancyDetailsPage/index.jsx
Updated tasks and button on tenancy details page to show only for members of groups: 'HOUSING_OFFICER', 'AREA_HOUSING_MANAGER', 'DEV_TEAM'
> Sv 140/get task by tag ref

- cypress/FakeSVapi.js
- cypress/fixtures/rentTransactions.json
- cypress/integration/pages/tenancyDetails/tenancyDetails.spec.js
- src/app/Components/Details/RentTransactions/index.jsx
- src/app/Components/Details/TenancyProcesses/index.jsx
- src/app/Gateways/FetchTransactions.js
- src/app/Gateways/index.js
- src/app/Pages/TenancyDetailsPage/index.jsx
- Added rent transactions on tenancy details page
- Added new component for rent transactions
- Updated TenancyProcesses component
> Sv 137/rent details

- cypress/fixtures/searchAddress.json
- cypress/integration/pages/searchAddressResults.spec.js
- src/app/Components/Results/AddressResults/index.jsx
- src/app/Pages/AddressResultsPage/index.jsx
> Sort tenancies by address on address results page

- cypress/integration/pages/results.spec.js
- cypress/integration/pages/searchAddress.spec.js
- src/app/Components/Tenant/index.jsx
- src/app/Pages/SearchPage/index.jsx
- Updated text, label, and button text on search page
- Updated date of birth to display a message when the dob doesn't exist
> Update text, label and button text on search page

- cypress/integration/pages/searchAddressResults.spec.js
- src/app/Components/Results/AddressResults/index.jsx
- src/app/Pages/SearchPage/index.jsx
- src/app/lib/Utils.js
- Updated text for tenure type to show without code and abbreviations
- Removed user groups for search by address
> Update tenure type text and remove groups for search by address

- cypress/integration/acceptance/search.spec.js
- src/app/Pages/SearchPage/index.jsx
- Add error message when trying to search by name with no name entered
> Search by name error message

- src/app/Components/Details/RentTransactions/index.jsx
- src/app/Components/Details/RentTransactions/index.scss
- Added pagination for rent transactions
> Add pagination for rent transactions
